import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Wishlist",
    description: "Generated by create next app",
    other: {
      "fc:miniapp": JSON.stringify({
        version: "next",
        imageUrl: "https://demo-wishlist-mini-app.vercel.app/banner.png",
        button: {
          title: `Start Playing!`,
          action: {
            type: "launch_miniapp",
            name: "Wishlist me",
            url: "https://demo-wishlist-mini-app.vercel.app",
            splashImageUrl:
              "https://demo-wishlist-mini-app.vercel.app/image.png",
            splashBackgroundColor: "#000000"
          }
        }
      })
    }
  };
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${geistMono.variable} antialiased `}>{children}</body>
    </html>
  );
}
